export enum SCENE {
  LOFI_CAFE = "LOFI_CAFE",
  BOOK_CAFE = "BOOK_CAFE",
  BEDROOM = "BEDROOM",
  PLANE = "PLANE",
  LAKE_HOUSE = "LAKE_HOUSE",
  IN_THE_WOODS = "IN_THE_WOODS",
  SEOUL = "SEOUL",
  AM_I_DREAMING = "AM_I_DREAMING",
  COZY_STUDIO = "COZY_STUDIO",
}

export enum SOUND {
  RAIN = "RAIN",
  TRAFFIC = "TRAFFIC",
  KEYBOARD = "KEYBOARD",
  PEOPLE = "PEOPLE",
  TRAIN = "TRAIN",
  THUNDER = "THUNDER",
  FOREST_NIGHT = "FOREST_NIGHT",
  CAMPFIRE = "CAMPFIRE",
  PLANE = "PLANE",
  BIRD = "BIRD",
}

export enum PLACE {
  OUT_SIDE = "OUT_SIDE",
  IN_SIDE = "IN_SIDE",
  SPAPCE = "SPACE",
  UNDER_WATER = "UNDER_WATER",
}

export enum TIME {
  DAY = "DAY",
  NIGHT = "NIGHT",
}

export enum WEATHER {
  RAIN = "RAIN",
  STOP_RAIN = "STOP_RAIN",
}
